"""""""""""""
" My .vimrc "
"""""""""""""

"""" VISUAL STUFF
" set colorscheme
colorscheme herald
" use syntax processing
syntax enable
" use filetype plugins
filetype plugin on
filetype indent on
" show line numbers
"set number
" show latest command
set showcmd 
" show cursor line
set cursorline
" show tab-completion matches
set wildmenu
" highlight matching braces (kind of annoying with blinking cursor)
set showmatch
" (to turn off) let g:loaded_matchparen=1
" display current position
set ruler
" always show status line
set laststatus=2
" format the status line
"set statusline=%F\ %y\ cwd:%{getcwd()}\ %l\,%v\ %P
set statusline=%F\ %y\ %l\,%v\ %P
"use line wrapping
set wrap
""""

"""" FILE FORMAT, ENCODING
" make unix default file type
set ffs=unix,dos,mac
" use utf8 encoding
set encoding=utf8
""""

"""" SPACES, TABS, INDENTING
" set default shift and tab width to 4 spaces
set shiftwidth=4
set tabstop=4
" convert tabs to spaces
set expandtab
" use smart tabbing
set smarttab
" use automatic indenting
set autoindent
" use smart indenting
set smartindent
" make backspace work properly
set backspace=2
"set backspace=eol,indent,start
""""

"""" SEARCHING
" highlight search matches
set hlsearch
" search while typing
set incsearch
" pattern is case-sensitive only if it includes uppercase
set ignorecase
set smartcase
"use magic for regex
set magic
""""

"""" FOLDING
" enable folding
set foldenable
" set initial fold level
set foldlevel=0
" set maximum number of nested folds
set foldnestmax=10
" set fold method
set foldmethod=indent
""""

"""" SYSTEM
" detect changes made externally
set autoread
"don't automatically create backup files
set nobackup
set noswapfile
set nowritebackup
""""

"""" ERRORS
"turn off error bells
set noerrorbells
set novisualbell
set t_vb=
""""

"""" MISC
" disable auto-commenting
"autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
""""

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" VIM-LATEX
"
" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
filetype plugin on

" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

"set default target format to pdf
let g:Tex_DefaultTargetFormat='pdf'
"let g:Tex_CompileRule_pdf='pdflatex -interaction=nonstopmode $*'
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
